#version: '1'
services:
  ghdata:
    image: ghdata:1.0
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    image: nginx
    depends_on:
      - ghdata
    ports:
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
volumes:
  postgres-data:
    driver: local